### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tvaivods** [awesmubarak/koboanki#6]
An error is displayed upon launching Tools > Import KOBO wordlist.

Debug info:
Anki 2.1.46 (94913ec2) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-08-10 20:49:36
Add-ons possibly involved: ⁨Koboanki v200⁩

Caught exception:
Traceback (most recent call last):
  File "/home/username/.local/share/Anki2/addons21/197599239/__init__.py", line 170, in koboanki_menu_action
    if len(config["languageList"]) == 0:
TypeError: 'NoneType' object is not subscriptable

**Comment by awesmubarak** [comment]
Thanks for raising this issue. Could you copy over your config for the addon please?

**Comment by awesmubarak** [comment]
Okay I've published a new release (v2.0.1) that should fix the issue. Lmk if it doesn't fix or causes some other issues :)
